export const actionTypes = {
	POST_NOTE: 'POST_NOTE',
	ERROR_POST_NOTE: 'ERROR_POST_NOTE',
	SUCCESS_POST_NOTE: 'SUCCESS_POST_NOTE_NOTE',

	FETCH_HISTORY: 'FETCH_HISTORY',
	SUCCESS_FETCH_HISTORY: 'SUCCESS_FETCH_HISTORY',
	ERROR_FETCH_HISTORY: 'ERROR_FETCH_HISTORY',
	SET_HISTORY: 'SET_HISTORY',
	FILTER_HISTORY: 'FILTER_HISTORY',
};
